Repository operator-framework/operator-controller, pull requests merged in 2025-05, with the labels that each got.

#1942 ✨ add NetworkPolicy objects for catalogd and operator-controller
  config/base/catalogd/manager/kustomization.yaml
  config/base/catalogd/manager/network_policy.yaml
  config/base/catalogd/manager/service.yaml
  config/base/operator-controller/manager/kustomization.yaml
  config/base/operator-controller/manager/network_policy.yaml
  test/e2e/metrics_test.go
Labels: lgtm

#1954 :bug: Add path to job workflow for go-verdiff
  .github/workflows/go-verdiff.yaml
Labels: lgtm, approved

#1955 :bug: Ease CI requirements for go-verdiff and codecov
  .github/workflows/go-verdiff.yaml
  codecov.yml
Labels: lgtm, approved

#1964 :seedling: Allow override of go-verdiff result via label
  .github/workflows/go-verdiff.yaml
  hack/tools/check-go-version.sh
Labels: lgtm, approved

#1963 :seedling: Update to kustomize v5
  .bingo/Variables.mk
  .bingo/kustomize.mod
  .bingo/kustomize.sum
  .bingo/variables.env
Labels: lgtm, approved

#1968 🌱 Refactor rukpack package for configurable registry+v1 rendering behavior
  cmd/operator-controller/main.go
  internal/operator-controller/applier/helm.go
  internal/operator-controller/applier/helm_test.go
  internal/operator-controller/rukpak/bundle/registryv1.go
  internal/operator-controller/rukpak/bundle/source/source.go
  internal/operator-controller/rukpak/bundle/source/source_test.go
  internal/operator-controller/rukpak/convert/helm.go
  internal/operator-controller/rukpak/convert/helm_test.go
  internal/operator-controller/rukpak/convert/registryv1_test.go
  internal/operator-controller/rukpak/convert/testdata/combine-properties-bundle/manifests/csv.yaml
  internal/operator-controller/rukpak/convert/testdata/combine-properties-bundle/metadata/annotations.yaml
  internal/operator-controller/rukpak/convert/testdata/combine-properties-bundle/metadata/properties.yaml
  internal/operator-controller/rukpak/render/registryv1/generators/generators.go
  internal/operator-controller/rukpak/render/registryv1/generators/generators_test.go
  internal/operator-controller/rukpak/render/registryv1/generators/resources.go
  internal/operator-controller/rukpak/render/registryv1/generators/resources_test.go
  internal/operator-controller/rukpak/render/registryv1/registryv1.go
  internal/operator-controller/rukpak/render/registryv1/registryv1_test.go
  internal/operator-controller/rukpak/render/registryv1/validators/validator.go
  internal/operator-controller/rukpak/render/registryv1/validators/validator_test.go
  internal/operator-controller/rukpak/render/render.go
  internal/operator-controller/rukpak/render/render_test.go
  internal/operator-controller/rukpak/util/testing/testing.go
  test/convert/generate-manifests.go
Labels: lgtm, approved

#1969 :sparkles: Add openshift-serviceca certificate provider
  cmd/operator-controller/main.go
  internal/operator-controller/features/features.go
  internal/operator-controller/rukpak/render/certproviders/openshift_serviceca.go
  internal/operator-controller/rukpak/render/certproviders/openshift_serviceca_test.go
Labels: lgtm, approved

#1979 🐛 fix: don't template registry+v1 manifests
  internal/operator-controller/rukpak/convert/helm.go
  test/e2e/cluster_extension_install_test.go
  testdata/images/bundles/test-operator/v1.0.0/manifests/bundle.configmap.yaml
Labels: lgtm, approved

#1982 :seedling: Ease CI requirements for codecov patch
  codecov.yml
Labels: lgtm, approved

#1983 :bug: fix install and upgrade e2es
  test/e2e/cluster_extension_install_test.go
  testdata/images/bundles/test-operator/v1.0.0/manifests/bundle.configmap.yaml
  testdata/images/bundles/test-operator/v2.0.0/manifests/bundle.configmap.yaml
  testdata/images/bundles/test-operator/v2.0.0/manifests/olm.operatorframework.com_olme2etest.yaml
  testdata/images/bundles/test-operator/v2.0.0/manifests/testoperator.clusterserviceversion.yaml
  testdata/images/bundles/test-operator/v2.0.0/metadata/annotations.yaml
  testdata/images/catalogs/test-catalog/v2/configs/catalog.yaml
  testdata/push/push.go
Labels: lgtm, approved

#1973 📖 Add NetworkPolicy doc
  docs/draft/api-reference/network-policies.md
Labels: lgtm, approved

#1974 :sparkles: Update releaser to use env variables
  .gitignore
  .goreleaser.yml
  Makefile
Labels: lgtm, approved

#1997 :bug: Fix webhook service rotation to renew within 24h of expiry
  internal/operator-controller/rukpak/render/certproviders/certmanager.go
  internal/operator-controller/rukpak/render/certproviders/certmanager_test.go
Labels: lgtm, approved

#1999 :seedling: Bundle renderer refactor webhook service related function and attribute naming
  internal/operator-controller/rukpak/render/certprovider.go
  internal/operator-controller/rukpak/render/certprovider_test.go
  internal/operator-controller/rukpak/render/certproviders/certmanager.go
  internal/operator-controller/rukpak/render/certproviders/certmanager_test.go
  internal/operator-controller/rukpak/render/certproviders/openshift_serviceca_test.go
  internal/operator-controller/rukpak/render/registryv1/generators/generators.go
  internal/operator-controller/rukpak/render/registryv1/generators/generators_test.go
  internal/operator-controller/rukpak/render/registryv1/registryv1.go
  internal/operator-controller/rukpak/render/registryv1/registryv1_test.go
Labels: lgtm, approved

#1950 📖 [doc] Initial draft doc preflight perms
  docs/draft/howto/rbac-permissions-checking.md
Labels: do-not-merge/hold, approved
